# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "chef/centos-6.5"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vbguest.auto_update = false

  config.vm.provision "file"
    source: "~/vagrant/files/git-config",
    destination: "~/.gitconfig"

  config.vm.provision "shell"
    path: "https://raw.githubusercontent.com/screencasts-pro/vagrant/master/scripts/centos-lamp.sh"

end
