# -*- mode: ruby -*-
# vi: set ft=ruby :

# List plugins dependencies
plugins_dependencies = %w( vagrant-gatling-rsync vagrant-docker-compose vagrant-vbguest vagrant-docker-login )
plugin_status = false
plugins_dependencies.each do |plugin_name|
  unless Vagrant.has_plugin? plugin_name
    system("vagrant plugin install #{plugin_name}")
    plugin_status = true
    puts " #{plugin_name}  Dependencies installed"
  end
end

# Restart Vagrant if any new plugin installed
if plugin_status === true
  exec "vagrant #{ARGV.join' '}"
else
  puts "All Plugin Dependencies allready installed"
end

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.hostname = "docker"
  config.vm.box = "bento/ubuntu-14.04"
  config.vm.network "private_network", ip: "192.168.1.100"

  config.vm.provider "virtualbox" do |v|
    v.name = "docker"
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.provision :shell, inline: "apt-get update"
  config.vm.provision :docker
  config.vm.provision :docker_login, username: "<user_name>", email: "<email_id>",   password: "<password>"
  config.vm.provision :docker_compose, yml: ["/vagrant/docker-compose.yml"]
end
