# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.8.0"

IP_CONSUL = "10.0.0.100"
IP_MASTER1 = "10.0.0.101"
IP_MASTER2 = "10.0.0.102"
IP_NODE1 = "10.0.0.103"
IP_NODE2 = "10.0.0.104"

$set_environment_variables = <<SCRIPT
echo "export IP_CONSUL='#{IP_CONSUL}'" >> /etc/profile.d/myvar.sh
echo "export IP_MASTER1='#{IP_MASTER1}'" >> /etc/profile.d/myvar.sh
echo "export IP_MASTER2='#{IP_MASTER2}'" >> /etc/profile.d/myvar.sh
echo "export IP_NODE1='#{IP_NODE1}'" >> /etc/profile.d/myvar.sh
echo "export IP_NODE2='#{IP_NODE2}'" >> /etc/profile.d/myvar.sh
SCRIPT

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/bionic64"
  #config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.provision "shell", path: "configure_docker_on_ubuntu.sh"
  config.vm.provision "shell", inline: $set_environment_variables, run: "always"

  config.vm.define "consul" do |consul|
    consul.vm.hostname = 'consul'
    consul.vm.define "swarm_consul"
    consul.vm.provider :virtualbox do |vb|
        vb.name = "swarm-consul"
    end
    consul.vm.network "private_network", ip: "#{IP_CONSUL}"
    consul.vm.provision "shell", inline: "docker run -d -p 8500:8500 --name=consul progrium/consul -server -bootstrap"
  end

  config.vm.define "manager1" do |manager1|
    manager1.vm.hostname = 'manager1'
    manager1.vm.define "swarm_manager1"
    manager1.vm.provider :virtualbox do |vb|
        vb.name = "swarm-manager1"
    end
    manager1.vm.network "private_network", ip: "#{IP_MASTER1}"
    manager1.vm.provision "shell", inline: "docker run -d -p #{IP_MASTER1}:4000:4000 swarm manage -H :4000 --replication --advertise #{IP_MASTER1}:4000 consul://#{IP_CONSUL}:8500"
  end

  config.vm.define "manager2" do |manager2|
    manager2.vm.hostname = 'manager2'
    manager2.vm.define "swarm_manager2"
    manager2.vm.provider :virtualbox do |vb|
        vb.name = "swarm-manager2"
    end
    manager2.vm.network "private_network", ip: "#{IP_MASTER2}"
    manager2.vm.provision "shell", inline: "docker run -d -p #{IP_MASTER2}:4000:4000 swarm manage -H :4000 --replication --advertise #{IP_MASTER2}:4000 consul://#{IP_CONSUL}:8500"
  end

  config.vm.define "node1" do |node1|
    node1.vm.hostname = 'node1'
    node1.vm.define "swarm_node1"
    node1.vm.provider :virtualbox do |vb|
        vb.name = "swarm-node1"
    end
    node1.vm.network "private_network", ip: "#{IP_NODE1}"
    node1.vm.provision "shell", inline: "docker run -d swarm join --advertise=#{IP_NODE1}:2375 consul://#{IP_CONSUL}:8500"
  end

  config.vm.define "node2" do |node2|
    node2.vm.hostname = 'node2'
    node2.vm.define "swarm_node2"
    node2.vm.provider :virtualbox do |vb|
        vb.name = "swarm-node2"
    end
    node2.vm.network "private_network", ip: "#{IP_NODE2}"
    node2.vm.provision "shell", inline: "docker run -d swarm join --advertise=#{IP_NODE2}:2375 consul://#{IP_CONSUL}:8500"
  end

end
