# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "chef/centos-6.5"
  config.vbguest.auto_update = false
  config.vm.provision "file"
    source: "~/vagrant/files/git-config",
    destination: "~/.gitconfig"
  config.vm.provision "shell"
    path: "https://raw.githubusercontent.com/screencasts-pro/vagrant/master/scripts/centos-common.sh"

  config.vm.define "web" do |web|
  	web.vm.hostname = "web-server"
  	web.vm.network "forwarded_port", guest: 80, host: 8080
  	web.vm.network "private_network", ip: "192.168.10.2"
  	web.vm.provision "shell"
    	path: "https://raw.githubusercontent.com/screencasts-pro/vagrant/master/scripts/centos-web.sh"
  end

  config.vm.define "db" do |db|
  	db.vm.hostname = "database-server"
  	db.vm.network "private_network", ip: "192.168.10.3"
  	db.vm.provision "shell"
    	path: "https://raw.githubusercontent.com/screencasts-pro/vagrant/master/scripts/centos-database.sh"
  end

end
